
# Project information
site_url: https://sslajpah.github.io/ros-docs/
site_author: Sebastjan Slajpah
site_description: ROS introduction with examples
# Repository
repo_name: sslajpah/ros-docs
repo_url: https://github.com/sslajpah/ros-docs

site_name: ROS DOCS
