
# Project information
site_url: https://sslajpah.github.io/ros-docs/
site_author: Sebastjan Slajpah
site_description: ROS introduction.
# Repository
repo_name: sslajpah/ros-docs
repo_url: https://github.com/sslajpah/ros-docs

site_name: ROS DOCS
nav:
    - Introduction to ROS: 'introduction/index.md'
    - ROS na RaspberryPi4: 'additional/index.md'
    - Sick NanoScan3: 'additional/sick.md'
    - Linux ukazi: 'additional/linux.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
